### PR TITLE
Resolves #14: Add applicant status

### LINKED ISSUE #14: Create new database column for applicant status

### PR DESCRIPTION
**Pull request by liusteph**
Added a new column to the Document database table to store applicant status.

Resolves #14

### CODE REVIEW

**Review by carsonstuart — COMMENTED** [review]
LGTM steph

**Review by whuang1202 — APPROVED** [review]
Functions as intended, good

**Review by rmartini24 — APPROVED** [review]
LGTM

**Comment by n8thanwai** [comment]
LGTM

**Review by n8thanwai — COMMENTED** [review]
LGTM

**Pull request merged**
