### PR TITLE
Resolves #16: Update Applicant Status in Database with added tweaks to the documentDao file to record updates for documents regarding the status

### LINKED ISSUE #16: Update applicant status in database

### PR DESCRIPTION
**Pull request by whuang1202**
In the documentDao file, we now call get/set status accordingly and also call it with the SQL function inside the get.

### CODE REVIEW

**Review by carsonstuart — APPROVED** [review]
Looks good william

**Review by liusteph — APPROVED** [review]
LGTM

**Review by n8thanwai — APPROVED** [review]
LGTM

**Review by rmartini24 — APPROVED** [review]
LGTM

**Pull request merged**
