### PR TITLE
Resolves #26 so that new applicant status is shown in the language input

### LINKED ISSUE #26: Allow status on form be represented applicants table

### PR DESCRIPTION
**Pull request by n8thanwai**
Changed language input on making new applicants to status input which was represented in the applicant table. I also changed the database to allow for new inputs.

### CODE REVIEW

**Review by carsonstuart — APPROVED** [review]
Looks good Nathaniel

**Review by liusteph — APPROVED** [review]
very cool

**Review by rmartini24 — APPROVED** [review]
LGTM i guess

**Review by whuang1202 — APPROVED** [review]
Huge Ws

**Pull request merged**
