### PR TITLE
Fixed failing tests and added more unit tests

### PR DESCRIPTION
**Pull request by liusteph**
Added missing files that the tests were expecting. Also added an additional unit test for checking applicant status. Automated testing should now pass.

### CODE REVIEW

**Review by rmartini24 — APPROVED** [review]
LGTM!

**Review by whuang1202 — APPROVED** [review]
Nice unit tests

**Review by carsonstuart — APPROVED** [review]
LGTM

**Review by n8thanwai — APPROVED** [review]
LGTM

**Pull request merged**
