### PR TITLE
Cosmetic changes and clean up

### PR DESCRIPTION
**Pull request by rmartini24**
Removed dashboard.html file (created when we were trying to make a kanban dashboard) since it's necessary, added a citation of where we got some of the code from for the dashboard, and removed dead code that we commented out.

Does not resolve a specific issue.

### CODE REVIEW

**Review by liusteph — APPROVED** [review]
LGTM

**Review by liusteph — APPROVED** [review]
LGTM

**Review by whuang1202 — APPROVED** [review]
works

**Review by carsonstuart — APPROVED** [review]
Good stuff R dog

**Review by n8thanwai — APPROVED** [review]
LGTM

**Pull request merged**
